# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 66c4175159b2b2357c33214796af1a7b6bc2f4c3f23baa72900cdf4e7bc32176a9d1e9afda398ee0816af9c041cd87a720ddb509802ba38f231406f61b39c01c

test:
  secret_key_base: 55943b304bf764fa7bc9fef50ed9ed43a8d30b6d725779545191f9d7714a3dabd6f923b957bcfbdae91a154e823b52eed9a0cf25890e8b9198dea903d16a6e04

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
